package xyz.fakestore.payments

import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import org.apache.kafka.clients.producer.ProducerRecord
import org.apache.kafka.common.header.internals.RecordHeader
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.kafka.core.KafkaTemplate
import xyz.fakestore.payments.dto.UserPaymentRequest
import xyz.fakestore.payments.enumz.Currency
import xyz.fakestore.payments.enumz.Topic
import xyz.fakestore.payments.persistence.PaymentMethodRepository
import java.math.BigDecimal
import java.math.RoundingMode
import java.util.UUID
import java.util.UUID.randomUUID

@SpringBootTest
class GenerateTestMessages {

    @Autowired
    private lateinit var kafkaTemplate: KafkaTemplate<String, String>

    @Autowired
    private lateinit var paymentMethodRepository: PaymentMethodRepository

    private val mapper = jacksonObjectMapper().apply { registerModule(JavaTimeModule()) }

    @Test
    fun `generate payment request messages`() {
        val howManyMessages = 5
        val testUserId = UUID.fromString("00000000-0000-0000-0000-000000000001")

        // Provision some payment methods for the test user
        val methods = (1..3).map { paymentMethodRepository.save(paymentMethodRepository.generateRandom(testUserId)) }

        for (i in 1..howManyMessages) {
            val upm = methods.random()
            val traceId = randomUUID().toString().toByteArray()

            val userPaymentRequest = UserPaymentRequest(
                userPaymentRequestId = randomUUID(),    // generated by orders system
                orderId = randomUUID(),                 // generated by orders system
                userPaymentMethodId = upm.userPaymentMethodId,
                amount = BigDecimal(Math.random() * 500 + 1).setScale(2, RoundingMode.HALF_UP),
                currency = Currency.entries.random()
            )
            val userPaymentRequestJson = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(userPaymentRequest)
            println("Generated payment request message:\n${userPaymentRequestJson}\n")
            val record = ProducerRecord(
                Topic.ORDERS__PAYMENTS_PAYMENTREQUESTED.topic,
                null,
                userPaymentRequest.orderId.toString(),
                userPaymentRequestJson,
                listOf(RecordHeader("traceId", traceId))
            )
            kafkaTemplate.send(record)
        }
    }
}