package xyz.fakestore.payments.enumz

enum class Topic(val topic: String) {
    ORDERS__PAYMENTS_PAYMENTREQUESTED(Topics.Orders.PAYMENTS_PAYMENTREQUESTED),
    ORDERS__ORDER_CREATED(Topics.Orders.ORDER_CREATED),
    ORDERS__ORDER_UPDATED(Topics.Orders.ORDER_UPDATED),
    ORDERS__ORDER_CANCELLED(Topics.Orders.ORDER_CANCELLED),

    PAYMENTS__PAYMENT_PROCESSED(Topics.Payments.PAYMENT_PROCESSED),
    PAYMENTS__PAYMENT_REJECTED(Topics.Payments.PAYMENT_REJECTED),
    PAYMENTS__PAYMENT_FAILED(Topics.Payments.PAYMENT_FAILED),

    USERS__USER_CREATED(Topics.Users.USER_CREATED),
    USERS__USER_UPDATED(Topics.Users.USER_UPDATED),
    USERS__USER_DELETED(Topics.Users.USER_DELETED),

    CATALOG__PRODUCT_CREATED(Topics.Catalog.PRODUCT_CREATED),
    CATALOG__PRODUCT_UPDATED(Topics.Catalog.PRODUCT_UPDATED),
    CATALOG__PRODUCT_DELETED(Topics.Catalog.PRODUCT_DELETED),
    CATALOG__PRICING_UPDATED(Topics.Catalog.PRICING_UPDATED),

    SHIPMENTS__SHIPMENT_CREATED(Topics.Shipments.SHIPMENT_CREATED),
    SHIPMENTS__SHIPMENT_UPDATED(Topics.Shipments.SHIPMENT_UPDATED),
    SHIPMENTS__SHIPMENT_DELIVERED(Topics.Shipments.SHIPMENT_DELIVERED),
    SHIPMENTS__SHIPMENT_FAILED(Topics.Shipments.SHIPMENT_FAILED),
}